source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'Combine' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end

#https://developers.google.com/admob/ios/quick-start#cocoapods